server:
  port: 8081
spring:
  application:
    name: demobankcomm
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demoBankComm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # 10.10.129.211 替换 127.0.0.1
    username: root
    password: a05586947521
  redis:
    host: 127.0.0.1
    port: 6379
    password: penghui
    lettuce:
      pool:
        max-active: 200
        max-idle: 200
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.bankcomm.demobankcomm.entity # ?????
  configuration:
    cache-enabled: false
    local-cache-scope: statement # 关闭一级缓存
logging:
  level:
    com.bankcomm: debug
  pattern:
    console: "%d{mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

remote:
  redis:
    host: redis-18909.c74.us-east-1-4.ec2.redns.redis-cloud.com
    port: 18909
    password: lnm4d66Fp3hJQ7uktxbv8TOSejCwUqQI
    lettuce:
      pool:
        max-active: 200
        max-idle: 200
        min-idle: 1
        time-between-eviction-runs: 10s
