---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Phantom Sean.
--- DateTime: 2024/7/19 13:39
---
-- Lua脚本
local userId = KEYS[1]
local userSetKey = KEYS[2]
local remainKey = KEYS[3]

-- 检查用户是否已经下单
if redis.call("SISMEMBER", userSetKey, userId) == 1 then
    return "不允许重复下单" .. userId
end

-- 检查剩余票量
local remain = redis.call("GET", remainKey)
if remain == "0" then
    return "售罄" .. userId
end

-- 扣减一张票
redis.call("DECR", remainKey)

-- 将用户加入已购票集合
redis.call("SADD", userSetKey, userId)

return "购票成功" .. userId
