server:
  port: 8081
spring:
  application:
    name: demobankcomm
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demoBankComm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: a05586947521
  redis:
    host: 127.0.0.1
    port: 6379
    password: penghui
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.bankcomm.demobankcomm.entity # ?????
logging:
  level:
    com.bankcomm: debug
    org.springframework.data.redis.connection.jedis.JedisConnection: debug
    org.springframework.data.redis.core.RedisTemplate: debug
  pattern:
    dateformat: mm:ss.SSS
